### ISSUE TITLE
Can you provide an erd diagramm

### ISSUE THREAD

**Issue by jimmyMaci** [lightblueseas/resource-bundles-data#4]
Hi there,

do you have an erd diagramm from this database?

Cheers
Jim

**Comment by astrapi69** [comment]
Hi Jim,

i create one here it is:

![erd-diagramm-resourcesbundles](https://cloud.githubusercontent.com/assets/1822320/24070510/2dd5f60c-0bbf-11e7-8524-5bfd28c0de27.png)

I hope this is what you expect.

King regards
asterios

**Comment by astrapi69** [comment]
I will push this image to the repository and close this issue.

**Comment by astrapi69** [comment]
Hi Jim,

here is the new erd-diagramm. I added the default locale to the bundle application:

![erd-diagramm-resource-bundles](https://cloud.githubusercontent.com/assets/1822320/24324278/d6d0cc90-1183-11e7-9417-11473d57913d.png)

Cheers
asterios
